Atm
AEGarten/CS401_SU21_BankProj pull request #33
Opened 2021-07-12 14:32 UTC by Jubiey

Updated transferFunds and viewBalance methods

2021-07-12 18:37 UTC, AEGarten commented on ATM/src/ATM.java
> +		message.perform = Process.WITHDRAWAL;
From what account will the withdrawal happen?

2021-07-12 18:38 UTC, AEGarten requested changes
Getting closer. Message for Withdrawal needs to indicate from which account will the withdrawal take place.

2021-07-13 19:09 UTC, hle95 approved these changes

2021-07-13 19:37 UTC, AEGarten approved these changes
A good first step. Eventually ATM should be able to figure somethings out. Like if an account's positiveStatus is false, don't allow withdrawal. Or if there is only one account (or only one account with a true positiveStatus), then don't allow transfer. Stuff like that.

2021-07-13 19:38 UTC, merged